name: Release

on:
  push:
    tags: ['*.*.*']
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  tests:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
    with:
      cache: false

  wheels:
    permissions:
      contents: read
    uses: ./.github/workflows/wheels.yml
    with:
      cache: false

  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [tests, wheels]
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: wheels
      - name: Publish to PyPI
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing *
